server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${hm.mysql.url}
    username: ${hm.mysql.username}
    password: ${hm.mysql.password}
  redis:
    host: ${hm.redis.host}
    port: ${hm.redis.port}
    # password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: NON_NULL # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug